# Generated by Django 3.1.4 on 2021-09-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_student_inscription_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='classes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
