# Generated by Django 3.1.2 on 2021-09-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
