# Generated by Django 3.1.2 on 2021-09-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20210907_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='bac_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='bac_type',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='num_tel',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
