# Generated by Django 3.1.2 on 2021-09-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20210907_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='num_tel',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='num_whatsapp',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
